# Generated by Django 3.0.3 on 2020-11-01 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osnovnipodaci', '0005_delete_objekt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zaposlenik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=44, null=True)),
                ('prezime', models.CharField(max_length=44, null=True)),
                ('telefon', models.CharField(max_length=15)),
                ('radno_mjesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osnovnipodaci.RadnoMjesto')),
            ],
            options={
                'verbose_name_plural': 'Zaposlenici',
            },
        ),
    ]
