# Generated by Django 3.0.3 on 2020-11-02 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaposleni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zaposlenik',
            options={'verbose_name_plural': 'Zaposleni'},
        ),
    ]
