# Generated by Django 3.0.3 on 2020-11-02 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strojevi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaniranoOdrzavanje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(null=True)),
                ('opis_posla', models.TextField(null=True)),
                ('vrijeme_rada', models.TimeField(null=True)),
                ('stroj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strojevi.Stroj')),
            ],
            options={
                'verbose_name_plural': 'Planirana održavanje',
            },
        ),
    ]
