# Generated by Django 3.0.3 on 2020-11-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skladiste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervnidio',
            name='proizvodjac',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rezervnidio',
            name='specifikacije',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
