# Generated by Django 3.0.3 on 2020-11-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadnoMjesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=44)),
            ],
            options={
                'verbose_name_plural': 'Radna mjesta',
            },
        ),
    ]
