# Generated by Django 3.0.3 on 2020-11-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osnovnipodaci', '0003_auto_20201101_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lokacija',
            new_name='Objekt',
        ),
    ]
