# Generated by Django 3.0.3 on 2020-11-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osnovnipodaci', '0004_auto_20201101_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objekt',
        ),
    ]
