# Generated by Django 3.0.3 on 2020-11-01 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MjestoUTvornici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Mjesta u tvornici',
            },
        ),
        migrations.CreateModel(
            name='Stroj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('mjesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strojevi.MjestoUTvornici')),
            ],
            options={
                'verbose_name_plural': 'Strojevi',
            },
        ),
    ]
