# Generated by Django 3.0.3 on 2020-11-02 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zaposleni', '0002_auto_20201102_0111'),
        ('strojevi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadniNalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djelatnici', models.ManyToManyField(to='zaposleni.Zaposlenik')),
            ],
            options={
                'verbose_name_plural': 'Radni nalozi',
            },
        ),
        migrations.CreateModel(
            name='PrijavaKvara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(null=True)),
                ('opis_kvara', models.TextField(null=True)),
                ('stroj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strojevi.Stroj')),
            ],
            options={
                'verbose_name_plural': 'Prijava kvara',
            },
        ),
    ]
