# Generated by Django 3.0.3 on 2020-11-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalozi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prijavakvara',
            name='datum',
            field=models.DateField(null=True),
        ),
    ]
