# Generated by Django 3.0.3 on 2020-11-05 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skladiste', '0002_auto_20201102_0145'),
        ('osnovnipodaci', '0005_delete_objekt'),
        ('zaposleni', '0002_auto_20201102_0111'),
        ('nalozi', '0002_auto_20201102_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='radninalog',
            name='kraj_rada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='radninalog',
            name='kvar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nalozi.PrijavaKvara'),
        ),
        migrations.AddField(
            model_name='radninalog',
            name='opis_posla',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='radninalog',
            name='pocetak_rada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='radninalog',
            name='rezervni_dijelovi',
            field=models.ManyToManyField(null=True, to='skladiste.RezervniDio'),
        ),
        migrations.AddField(
            model_name='radninalog',
            name='vrsta_odrzavanja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osnovnipodaci.VrstaOdrzavanja'),
        ),
        migrations.AlterField(
            model_name='radninalog',
            name='djelatnici',
            field=models.ManyToManyField(null=True, to='zaposleni.Zaposlenik'),
        ),
    ]
