# Generated by Django 3.0.3 on 2020-11-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nalozi', '0003_auto_20201105_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='radninalog',
            name='datum',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
